project:
  type: website
  output-dir: docs

website:
  title: "Math & CP Class"
  sidebar:
    style: floating
    search: true
    contents:
      - section: "Математик"
        contents:
          - math/5.26.qmd
          - math/5.27.qmd
          - math/5.29.qmd
          - math/6.02.qmd
          - math/6.09.qmd
          - math/6.10.qmd
      - section: "Програмчлал"
        contents:
          - cp/cp1.qmd
          # - cp/cp2.qmd
  page-footer: "© 2025 Batsambuu Batbold"

format:
  html:
    theme: litera
    toc: true
lang: mn
