project:
  type: website
  output-dir: docs

website:
  title: "Math & CP Class"
  sidebar:
    style: floating
    search: true
    contents:
      - section: "Математик"
        contents:
          - math/5.26.qmd
          - math/5.27.qmd
          - math/5.29.qmd
          - math/6.02.qmd
          - math/6.09.qmd
          - math/6.10.qmd
          - math/6.11.qmd
          - math/7.14.qmd
      - section: "Програмчлал"
        contents:
          - cp/6.17.qmd
          - cp/6.18.qmd
          - cp/6.19.qmd
          - cp/6.20.qmd
      - section: "Англи хэл"
        contents:
          - english/6.17.qmd
          - english/6.18.qmd
          - english/6.19.qmd
          - english/6.20.qmd
      - section: "Сорил"
        contents: 
          - challenges/1.1.qmd
          - challenges/1.2.qmd
          - challenges/2.1.qmd
      
  page-footer: "© 2025 Batsambuu Batbold"

format:
  html:
    theme: flatly
    toc: true
lang: mn
