project:
  type: website
  output-dir: docs

website:
  title: "Lessons"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Math
        menu:
          - href: math/math1.qmd
            text: Lesson №1
      - text: CP
        menu:
          - href: cp/cp1.qmd
            text: Lesson №1
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



