---
title: "Геометрийн бусад леммүүд (/)"
format: html
lang: mn
---

# Симсоны Шулуун (Simson Lines)
$\triangle ABC$ гурвалжин ба дурын $P$ цэгийг авч үзье. $X$, $Y$, $Z$ цэгүүд нь $P$-ээс $BC$, $CA$, $AB$ шулуунуудад буулгасан перпендикуляруудын сууриад байг. Өмнө нь үзсэнчлэн $X$, $Y$, $Z$ цэгүүд нь нэг шулуун дээр орших гарцаагүй бөгөөд хүрэлцээтэй нөхцөл нь $P$ цэг $(ABC)$ багтаасан тойрог дээр орших юм. Хэрэв $P$ нь $(ABC)$ тойрог дээр оршиж байвал, энэ шулууныг $P$ цэгийн $\triangle ABC$-тэй харгалзах Симсоны шулуун гэнэ.

$\triangle ABC$ гурвалжны ортотөвийг $H$ гэж тэмдэглэе. $PX$ шулуун $(ABC)$ тойргийг дахин $K$ цэгт огтолно гэж үзье. Мөн $AH$ шулуун нь Симсоны шулуутай $L$ цэгт огтлолцоно гэж тэмдэглэе.

## Дасгал 1
Симсоны шулуун нь $AK$ шулуунтай параллель байгааг батал.

## Дасгал 2
$K$-г $BC$ шулуунд тэгш хэмтэй хувиргасан цэгийг $K'$ гэж тэмдэглэе. Тэгвэл $K'$ нь $\triangle PBC$ гурвалжны ортотөв болохыг батал.

## Дасгал 3
$LHXP$ нь параллелограмм болохыг харуул.

## Лемма 1 (Simson Line Bisection)

$\triangle ABC$ гурвалжны ортотөвийг $H$ гэж тэмдэглэе. Хэрэв $P$ нь $(ABC)$ багтаасан тойргийн цэг байвал, $P$ цэгийн Симсоны шулуун нь $PH$ хэрчмийг тэнцүү хуваана.

# Дотоод болон Гадаад багтсан тойргууд

## Лемма 1 (The Diameter of the Incircle)

$\triangle ABC$ гурвалжинд багтсан тойрог нь $BC$ талд $D$ цэгт шүргэж байг. $DE$ нь багтсан тойргийн диаметр бөгөөд $AE$ цацраг $BC$ талыг $X$ цэгт огтолно. Тэгвэл $BD = CX$ бөгөөд $X$ нь $A$-оройтой гадаад багтсан тойргийн $BC$ талтай шүргэлцэх цэг байна.

## Лемма 2 (Diameter of the Excircle)

Өмнөх дасгалын тэмдэглэгээний дагуу $XY$ нь $A$-оройтой гадаад багтсан тойргийн диаметр гэж үзье. Тэгвэл $D$ цэг нь $AY$ шулуун дээр оршихыг харуул.

## Лемма 3 (An Incircle Concurrency)

$\triangle ABC$ гурвалжинд багтсан тойргийн төвийг $I$, контакт гурвалжны оройнуудыг $D$, $E$, $F$ гэж тэмдэглэе. Хэрэв $M$ нь $BC$ талын дундаж цэг байвал $EF$, $AM$ шулуун болон $DI$ цацраг нь нэг цэгт огтлолцоно.


# Өндөрүүдийн дундаж цэгүүд

## Лемма 1 (Midpoint of Altitudes)

$\triangle ABC$ гурвалжинд багтсан тойргийн төвийг $I$, $A$-оройтой гадаад багтсан тойргийн төвийг $I_A$ гэж тэмдэглэе. Мөн $D$, $X$ нь тус тус багтсан болон гадаад багтсан тойргийн $BC$ талтай шүргэлцэх цэгүүд байг. Тэгвэл $DI_A$ ба $XI$ шулуунууд нь $A$ оройгоос $BC$ талд буулгасан өндрийн дундаж цэгт огтлолцоно.


# Изогонал ба изотомик хосмогууд

## Лемма 1 (Isogonal Conjugates)

$\triangle ABC$ гурвалжинд дурын $P$ цэг нь гурвалжны аль ч талтай нэг шулуун дээр байхгүй гэж үзье. Тэгвэл дараах нөхцлүүдийг хангах цорын ганц $P^*$ цэг оршин байна:

$$
\angle BAP = \angle P^*AC, \quad \angle CBP = \angle P^*BA, \quad \angle ACP = \angle P^*CB.
$$

Энэхүү $P^*$ цэгийг $P$-ийн **изогонал хосмог** гэнэ.

## Лемма 2 (Isotomic Conjugates)

$P$ цэг болон $\triangle ABC$ гурвалжин өгөгдсөн байг. $X$, $Y$, $Z$ нь $P$-с $BC$, $CA$, $AB$ талууд руу татсан чевиануудын суурь байг. $X'$-г $BC$ талын дундаж цэгт тэгш хэмтэй хувиргасан $X$-ийн дүр гэж авч үзье, мөн $Y'$, $Z'$-г $CA$, $AB$ талуудын дундаж цэгт тэгш хэмтэй хувиргасан $Y$, $Z$ цэгүүдийн дүрүүд гэж тодорхойлъё. Тэгвэл $AX'$, $BY'$, $CZ'$ шулуунууд нэг цэгт огтлолцоно. Тэр цэгийг $P$-ийн **изотомик хосмог** $P^t$ гэж нэрлэнэ.

## Теорем 1 (Isogonal Ratios)

$D$, $E$ нь $BC$ тал дээр орших цэгүүд бөгөөд $AD$, $AE$ нь изогонал чевианууд гэж үзье. Тэгвэл дараах харьцаа биелнэ:

$$
\frac{BD}{DC} \cdot \frac{BE}{EC} = \left( \frac{AB}{AC} \right)^2.
$$

# Симмедиан

Гурвалжны медианы изогоналыг **симмедиан** гэдэг. Гурвалжны гурван симмедиан шулуунуудын огтлолцлын цэгийг **симмедиан цэг** гэж нэрлэнэ.

## Лемма 1 (Constructing the Symmedian)

$X$-г $(ABC)$ тойргийн $B$ ба $C$ цэгүүдэд шүргэх шулуунуудын огтлолцлын цэг гэж авъя. Тэгвэл $AX$ шулуун нь симмедиан байна.

## Лемма 2 (Properties of the Symmedian)

$\triangle ABC$ гурвалжийг авч үзье. $B$ ба $C$ цэгүүдэд $(ABC)$ тойргийг шүргэх шулуунууд нь $X$ цэгт огтлолцоно. $AX$ шулуун $(ABC)$-г дахин $K$ цэгт огтолно, мөн $AX$ нь $BC$ талыг $D$ цэгт огтолно. Тэгвэл $AD$ нь $A$-оройн симмедиан бөгөөд дараах шинжүүд биелнэ:

(a) $KA$ нь $\triangle KBC$ гурвалжны $K$-оройн симмедиан.

(b) $\triangle ABK$ ба $\triangle AMC$ нь төсөөтэй гурвалжнууд.  

(c) Дараах харьцаа биелнэ:  
$$
\frac{BD}{DC} = \left( \frac{AB}{AC} \right)^2.
$$  

(d) Дараах харьцаа мөн биелнэ:  
$$
\frac{AB}{BK} = \frac{AC}{CK}.
$$  

(e) $(BCX)$ тойрог нь $AK$ хэрчмийн дундаж цэгээр дайрч өнгөрнө.  

(f) $BC$ шулуун нь $\triangle BAK$ гурвалжны $B$-оройн симмедиан бөгөөд мөн $\triangle CAK$-ийн $C$-оройн симмедиан.  

(g) $BC$ нь $\angle AMK$ өнцгийн дотоод биссектрис, $MX$ нь гадаад биссектрис.

## Лемма 3 (Symmedians in Cyclic Quadrilaterals)

$ABCD$ нь тойрогт багтсан дөрвөн өнцөгт байг. Дараах нөхцлүүд нь хоорондоо эквивалент байна:

(a) $AB \cdot CD = BC \cdot DA$.  

(b) $AC$ нь $\triangle DAB$ гурвалжны $A$-оройн симмедиан.

(c) $AC$ нь $\triangle BCD$ гурвалжны $C$-оройн симмедиан.

(d) $BD$ нь $\triangle ABC$ гурвалжны $B$-оройн симмедиан.

(e) $BD$ нь $\triangle CDA$ гурвалжны $D$-оройн симмедиан.


# Сегментэд багтсан тойргууд

## Лемма 1 (Circles Inscribed in Segments)

$AB$ нь $\Omega$ тойргийн нэг хөвч байг. $\omega$ нь $AB$ хөвчийг $K$ цэгт шүргэх бөгөөд $\Omega$ тойргийг $T$ цэгт дотоод байдлаар шүргэнэ. Тэгвэл $TK$ цацраг нь $AB$ нумын $T$-г агуулаагүй хэсгийн дундаж цэг болох $M$ цэгээр дайрна. Мөн $MA^2 = MB^2$ бөгөөд энэ нь $\omega$ тойргийн хувьд $M$ цэгийн зэрэгтэй тэнцүү байна.

## Лемма 2 (Curvilinear Incircle Chords)

$\triangle ABC$ гурвалжинг авъя, $D$ нь $AB$ тал дээр орших цэг байг. $\omega$ тойрог нь $CD$-г $L$ цэгт, $AB$-г $K$ цэгт, мөн $(ABC)$ тойргийг шүргэнэ гэж үзье. Тэгвэл $\triangle ABC$-ийн багтсан тойргийн төв $I$ нь $LK$ шулуун дээр оршино.

# Микстилинеар (mixtilinear) багтсан тойргууд

$\triangle ABC$ гурвалжны $A$-микстилинеар багтсан тойрог нь $(ABC)$ багтаасан тойргийг дотроос шүргэх, мөн $AB$, $AC$ талуудад шүргэх тойрог юм.


## Лемма 1 (Mixtilinear Incircles)

$\triangle ABC$ гурвалжинг авъя. Түүний $A$-микстилинеар тойрог нь $AB$, $AC$ талуудыг болон $(ABC)$ багтаасан тойргийг шүргэх ба шүргэлцэх цэгүүдийг $K$, $L$, $T$ гэж тэмдэглэе. Мөн дотоод багтсан тойргийн $BC$ талтай шүргэлцэх цэгийг $D$, $A$-оройн гадаад багтсан тойргийн $BC$-тэй шүргэлцэх цэгийг $E$ гэе. Дараах шинжүүд биелнэ:

(a) $KL$ хэрчмийн дундаж цэг $I$ нь $\triangle ABC$-ийн дотоод багтсан тойргийн төв.  

(b) $TK$, $TL$ шулуунууд нь $T$-г агуулаагүй $AB$, $AC$ нумуудын дундаж цэгүүдээр дайрдаг.  

(c) $TI$ шулуун нь $A$-г агуулагч $BC$ нумын дундаж цэгээр дайрдаг.  

(d) $\angle BAT = \angle CAE$.  

(e) $\angle BTA = \angle CTD$.  

(f) $BKIT$ болон $CLIT$ дөрвөн өнцөгтүүд нь тойрогт багтдаг.


# Бодлогууд

## Бодлого 1 (Hong Kong 1998)

$\angle PSR = 90^\circ$ бүхий $PQRS$ нь тойрогт багтсан дөрвөн өнцөгт байг. $H$ болон $K$ нь $Q$-оос $PR$ болон $PS$ шулуунуудад буулгасан перпендикуляруудын сууриуд гэж үзье. Тэгвэл $HK$ шулуун нь $QS$ хэрчмийг тэнцүү хуваана гэж батал. 

## Бодлого 2 (USAMO 1988/4)

$\triangle ABC$ гурвалжинд $I$ нь багтсан тойргийн төв байг. $IAB$, $IBC$, $ICA$ гурвалжнуудын багтаасан тойргийн төвүүдийг авч үзье. Тэгвэл эдгээр гурван цэг нь нэг тойрог дээр орших бөгөөд уг тойргийн төв нь $\triangle ABC$-ийн багтаасан тойргийн төв гэж батал.

## Бодлого 3 (USAMO 1995/3)

Адил хажуут биш, мөн тэгш өнцөгт биш $\triangle ABC$ гурвалжны багтаасан тойргийн төвийг $O$ гэж тэмдэглэе. $A_1$, $B_1$, $C_1$ нь $BC$, $CA$, $AB$ талуудын дундаж цэгүүд байг. $A_2$ нь $OA_1$ цацраг дээр орших цэг бөгөөд $OAA_1 \sim OA_2A$ гэсэн төсөөтэй гурвалжууд үүсэхээр байрласан байг. $B_2$, $C_2$ цэгүүдийг $OB_1$, $OC_1$ цацрагууд дээр адил аргаар тодорхойлъё. Тэгвэл $AA_2$, $BB_2$, $CC_2$ шулуунууд нэг цэгт огтлолцоно.

## Бодлого 4 (USA TST 2014)

Хурц өнцөгт $\triangle ABC$ гурвалжинг авъя. $X$ нь $(ABC)$ тойргийн $BC$ богино нум дээр орших хувьсах цэг байг. $P$, $Q$ нь $X$-ээс $CA$, $CB$ шулуунуудад буулгасан перпендикуляруудын сууриуд байг. $PQ$ шулуун ба $B$-ээс $AC$ шулуунд буулгасан перпендикулярын огтлолцлын цэгийг $R$ гэж тэмдэглэе. $P$ цэгээр дайрч $XR$ шулуунтай параллель шулууныг $\ell$ гэж нэрлэе. Тэгвэл $X$ цэг $BC$ богино нумын дагуу өөрчлөгдөхөд $\ell$ шулуун нь тогтмол нэг цэгээр дайрч өнгөрнө гэж батал.

## Бодлого 5 (USA TST 2011/1)

Хурц өнцөгт, адил хажуут биш $\triangle ABC$ гурвалжинд $D$, $E$, $F$ цэгүүд нь $AD \perp BC$, $BE \perp CA$, $CF \perp AB$ байх нөхцлөөр $BC$, $CA$, $AB$ талууд дээр оршиж байг. Эдгээр өндөрүүд $H$ ортотөвд огтлолцоно. $P$, $Q$ цэгүүд нь $EF$ хэрчмийн дээр орших ба $AP \perp EF$, $HQ \perp EF$ байна. $DP$ ба $QH$ шулуунууд $R$ цэгт огтлолцоно. Тэгвэл $\frac{HQ}{HR}$ харьцааг ол.

## Бодлого 6 (ELMO Shortlist 2012)

Тойргууд $\Omega$ ба $\omega$ нь $C$ цэгт дотоод байдлаар шүргэлцдэг байг. $\Omega$ тойргийн $AB$ хөвч нь $\omega$ тойрогт $E$ цэгт шүргэх ба $E$ нь $AB$ хөвчийн дундаж цэг. $\omega_1$ нь $\Omega$, $\omega$, мөн $AB$ хөвчтэй тус тус $D$, $Z$, $F$ цэгүүдэд шүргэх тойрог байг. $CD$ цацраг ба $AB$ цацраг $P$ цэгт огтолно. $M \neq C $ нь $AB$ урт нумын дундаж цэг байг. Тэгвэл дараах тэнцэтгэл биелнэ:

$$
\tan \angle ZEP = \frac{PE}{CM}.
$$

## Бодлого 7 (USAMO 2011/5)

$P$ нь гүдгэр дөрвөн өнцөгт $ABCD$-ийн дотор орших цэг байг. $ABCD$-ийн дотор орших $Q_1$, $Q_2$ цэгүүд дараах өнцгийн нөхцлүүдийг хангана:

- $\angle Q_1BC = \angle ABP$,  
- $\angle Q_1CB = \angle DCP$,  
- $\angle Q_2AD = \angle BAP$,  
- $\angle Q_2DA = \angle CDP$.

Тэгвэл $Q_1Q_2 \parallel AB$ байх гарцаагүй бөгөөд хүрэлцээтэй нөхцөл нь $Q_1Q_2 \parallel CD$ гэж батал.

## Бодлого 8 (Japanese Olympiad 2009)

$\triangle ABC$ нь $(\Omega)$ тойрогт багтсан байг. $O$ төвтэй тойрог нь $BC$ талд $P$ цэгт шүргэж, $A$-г агуулаагүй $BC$ нумд дотоод байдлаар $Q$ цэгт шүргэнэ. Хэрэв $\angle BAO = \angle CAO$ бол $\angle PAO = \angle QAO$ байхыг харуул.

## Бодлого 9 

$\triangle ABC$ гурвалжинд багтсан тойрог нь $BC$ талд $D$ цэгт шүргэж байг. $T$ нь $(ABC)$ багтаасан тойрогт $A$-микстилинеар багтаасан тойрог шүргэж буй цэг байг. Тэгвэл $\angle BTA = \angle CTD$ гэдгийг харуул.

## Бодлого 10 (Vietnam TST 2003/2)

$\triangle ABC$ нь адил хажуут биш гурвалжин байг. Багтаасан тойргийн төвийг $O$, багтсан тойргийн төвийг $I$ гэж тэмдэглэе. $H$, $K$, $L$ нь тус тус $A$, $B$, $C$ оройгоос буулгасан өндөрүүдийн сууриуд байг. $A_0$, $B_0$, $C_0$ нь $AH$, $BK$, $CL$ хэрчмүүдийн дундаж цэгүүд байна. Багтсан тойрог нь $BC$, $CA$, $AB$ талуудыг $D$, $E$, $F$ цэгүүдэд шүргэнэ. Тэгвэл $A_0D$, $B_0E$, $C_0F$, $OI$ шулуунууд нэг цэгт огтлолцоно гэж батал.

## Бодлого 11 (Sharygin 2013)

$\triangle ABC$ гурвалжны багтсан тойрог нь $BC$, $CA$, $AB$ талуудыг тус тус $A'$, $B'$, $C'$ цэгүүдэд шүргэнэ. Багтсан тойргийн төв $I$-ээс $C$ оройн медианд буулгасан перпендикуляр $A'B'$ шулуутай $K$ цэгт огтолно. Тэгвэл $CK \parallel AB$ гэдгийг харуул.

## Бодлого 12 (APMO 2012/4)

Хурц өнцөгт $\triangle ABC$ гурвалжинг авъя. $D$ нь $A$ оройгоос $BC$ талд буулгасан перпендикулярын суурь, $M$ нь $BC$ талын дундаж цэг, $H$ нь $\triangle ABC$-ийн ортотөв байг. $E$ нь $\triangle ABC$-ийн багтаасан тойрог $(\Omega)$ болон $MH$ цацрагийн огтлолцлын цэг, $F$ нь $ED$ шулуун ба $(\Omega)$ тойргийн хоёр дахь огтлолцлын цэг байг ($F \ne E$). Тэгвэл дараах харьцаа биелнэ гэж батал:

$$
\frac{BF}{CF} = \frac{AB}{AC}.
$$

## Бодлого 13 (Shortlist 2002/G7)

Хурц өнцөгт $\triangle ABC$ гурвалжны багтсан тойрог $\omega$ нь $BC$ талд $K$ цэгт шүргэж байг. $AD$ нь өндөр ба $M$ нь $AD$ хэрчмийн дундаж цэг байна. $KM$ шулуун нь $\omega$ тойргийг $K$-оос өөр $N$ цэгт огтолно. Тэгвэл $\omega$ болон $\triangle BCN$ гурвалжны багтаасан тойрог нь $N$ цэгт хоорондоо шүргэлцэнэ гэж батал.
























