---
title: "Комбинаторикын хялбар бодлогууд (6/09)"
format: html
lang: mn
---

# Бодлогууд

## Бодлого 1 (AIME 1991)

Хүртвэр болон хуваарийнх нь үржвэр $20!$ байх $0$ болон $1$-ийн хооронд хэчнээн рациональ тоо байгаа вэ? Энд хүртвэр болон хуваарийг харилцан анхны гэж үзнэ.

## Бодлого 2

Эхний арван найман натурал тооноос аль ч хоёр тооных нь зөрүү ядаж $2$ байх таван тоог сонгох боломжийн тоог ол. 

## Бодлого 3 (AIME 1998)

$x_1 + x_2 + x_3 + x_4 = 98$ нөхцөлийг хангах **сондгой** эерэг бүхэл тоон эрэмбэлэгдсэн $(x_1, x_2, x_3, x_4)$ дөрвөлийн тоог ол.  

## Бодлого 4

$100$-аас хэтрэхгүй ямар ч $16$-н ялгаатай эерэг бүхэл тоонуудын хувьд $a + b = c + d$ байх ялгаатай $a, b, c, d$ тоонууд олдоно гэж батал. 

## Бодлого 5 (AIME 1996)

$7 \times 7$ даамны хөлгийн хоёр нүд нь шараар бусад нь ногооноор будагдсан байв. Эргэлтээр үүсэх будалтуудыг нэг гэж үзвэл хичээн ялгаатай будалт байгаа вэ?

## Бодлого 6 (MOSP 1997)

Үл огтлолцох $A$ ба $B$ олонлогуудын нэгдэл нь натурал тоонуудын олонлог байв. Бүх натурал тоо $n$-ийн хувьд дараах нөхцөлийг хангах ялгаатай $a, b > n$ олдоно гэж батал:

$$
\{a, b, a + b\} \subseteq A \quad \text{эсвэл} \quad \{a, b, a + b\} \subseteq B
$$

## Бодлого 7 (AIME 1986)

Өсөх $1, 3, 4, 9, 10, 12, 13, \dots$ дараалал нь $3$-ийн зэрэг эсвэл ялгаатай $3$-ийн зэргүүдийн нийлбэр болдог эерэг бүхэл тоонуудаас тогтоно. Энэ дарааллын $100$ дахь гишүүнийг ол.

## Бодлого 8 (AHSME 1989)

Нэг эгнээнд $7$ охин ба $13$ хөвгүүн жагссан гэж үзье. $S$ нь хөвгүүн болон охин зэрэгцэж зогссон газруудын тоо байг. Жишээлбэл, $ОХХОООХОХОООХОХООХОО$ жагсаалын хувьд $S = 12$. Бүх боломжит жагсаалыг авч үзсэн бол $S$-ийн дундаж утгыг ол.

## Бодлого 9 (AIME 1996)

Нэгэн уйдсан сурагч $1$-ээс $1024$ хүртэлх дугаартай хаалттай шүүгээнүүдийг эгнүүлсэн коридороор алхаж явав. Тэр $1$ дугаартай шүүгээг онгойлгоод, дараагийн хаалттай шүүгээг алгасах, тэрний дараах хаалттайг онгойлгох гэх мэтчилэн хаалттай шүүгээнүүдийг алгасах болон онгойлгох гэж ээлжилж явав. Коридорын төгсгөлд эрсний дараа тэрээр эргэж хараад дахиж алхав. Тэгэхдээ тэрээр хамгийн эхэнд таарсан хаалттай шүүгээг нээж, өмнөхийн адил хаалттай шүүгээнүүдийг алгасах болон онгойлгох гэж ээлжилж явав. Хэрвээ сурагч бүх шүүгээ онгойтол коридороор эргэж буцаж явсан бол тэр хамгийн сүүлд ямар дугаартай шүүгээг нээсэн бэ?

## Бодлого 10 (AIME 1990)

$T = \{ 9^k \ | \ k \in \mathbb{Z}, \ 0 \leq k \leq 4000 \}$ байг. Хэрвээ $9^{4000}$ нь $3817$ оронтой тоо ба эхний цифр нь $9$ бол $T$-ийн хэдэн элементийн эхний цифр $9$ вэ?


<!-- 
34
35
37
38
40
44
45
47
48
51
-->



