---
title: "Анхан шатны алгебрын бодлогууд №1 (8/06)"
format: html
lang: mn
---

# Бодлогууд

## Бодлого 1 (Romania 1974)

$a, b, c$ нь эерэг бодит тоонууд байг. Дараах тэгшитгэлийг $x$-ийн хувьд бод:

$$
\sqrt{(a+bx)} + \sqrt{(b+cx)} + \sqrt{(c+ax)} = \\ \sqrt{(b-ax)} + \sqrt{(c-bx)} + \sqrt{(a-cx)}
$$

## Бодлого 2

$x_0 = 3, x_1 = 4$ ба 
$$x_{n + 1} = x_{n - 1}^2 - nx_n, \quad n \in \mathbb{N}$$
бол $\{x_n\}$ дарааллын ерөнхий гишүүний томьёог ол.

## Бодлого 3 (AHSME 1999)

$\{x_n\}$ нь дараах нөхцөлүүдийг хангах бүхэл тоон дараалал байг:

* $i = 1, 2, \dots, n$-ийн хувьд $-1 \leq x_i \leq 2$
* $x_1 + x_2 + \dots + x_n = 19$
* $x_1^2 + x_2^2 + \dots + x_n^2 = 99$

Тэгвэл дараах илэрхийллийн хамгийн их болон хамгийн бага утгуудыг ол:

$$x_1^3 + x_2^3 + \dots + x_n^3$$

## Бодлого 4 (AIME 1997)

$f$ функц нь дараах байдлаар тодорхойлогдоно:


$$f(x) = \frac{ax + b}{cx + d}$$
энд $a, b, c, d$ нь тэг биш бодит тоонууд.

$f(19) = 19, \quad f(97) = 97$ ба $-\frac{d}{c}$-ээс бусад бүх $x$-ийн хувьд $f(f(x)) = x$ байв. Тэгвэл $f$-ийн утгын мужийг ол. 

## Бодлого 5

Бүх $a \geq b > 0$-ийн хувьд 

$$
\frac{(a - b)^2}{8a} \leq \frac{a+b}{2} - \sqrt{ab} \leq \frac{(a - b)^2}{8b}
$$
гэж батал.

## Бодлого 6 (St. Petersburg 1989)

Хэд хэдэн (дор хаяж хоёр) тэг биш тоонууд самбарт бичигдсэн байв. Хэн нэгэн $a, b$ гэсэн дурын хоёр тоог арилгаад оронд нь $a + \frac{b}{2}, b - \frac{a}{2}$ гэсэн тоонуудыг бичиж болно. Тэгвэл хэдэн ч ийм үйлдлийн дараа анх байсан тоонуудтай адилхан тоонууд гаргаж авч чадахгүй гэж батал. 

## Бодлого 7 (AIME 1986)

Олон гишүүнт 
$$
1 - x + x^2 - x^3 + \dots + x^{16} - x^{17}
$$
нь дараах хэлбэрт бичигдэж болно:

$$
a_0 + a_1y + a_2y^2 + \dots + a_{16}y^{16} + a_{17}y^{17}
$$
энд $y = x + 1$ ба $a_i$-ууд нь тогтмол. Тэгвэл $a_2$-г ол.

## Бодлого 8

$a,b,c$ нь ялгаатай тэг биш бодит тоонууд ба дараах нөхцөлийг хангана:

$$
a + \frac{1}{b} = b + \frac{1}{c} = c + \frac{1}{a}
$$

Тэгвэл $|abc| = 1$ гэж батал.

## Бодлого 9 (Putnam 1999)

Бүх $x$-ийн хувьд дараах нөхцөлийг хангах $f(x), g(x), h(x)$ олон гишүүнтүүдийг ол, эсвэл олдохгүй гэж батал:

$$
|f(x)| - |g(x)| + h(x) =
\begin{cases}
-1         &  x < -1 \\
3x + 2     & -1 \leq x \leq 0 \\
-2x + 2    &  x > 0
\end{cases}
$$

## Бодлого 10

Дараах нөхцөлийг хангах бүх $x$ бодит тоонуудыг ол:

$$
\frac{8^x + 27^x}{12^x + 18^x} = \frac{7}{6}
$$

## Бодлого 11 (Romania 1990)

Бүх $n$ эерэг бүхэл тоонуудын хувьд дараах нөхцөлийг хангах хамгийн бага эерэг бүхэл тоо $m$-ийг ол:

$$
\binom{2n}{n}^{\frac{1}{n}} < m
$$
