---
title: "Анхан шатны алгебрын бодлогууд №2 (8/12)"
format: html
lang: mn
---

# Бодлогууд

## Бодлого 1

$a, b, c, d, e$ нь дараах нөхцөлийг хангах эерэг бүхэл тоонууд байг:

$$
abcde = a + b + c + d + e
$$

Тэгвэл $\max\{a,b,c,d,e\}$-ийн хамгийн их боломжит утгыг ол.

## Бодлого 2

Дараах илэрхийллийг тооцоол:

$$
\frac{3}{1! + 2! + 3!} + \frac{4}{2! + 3! + 4!} + \dots + \frac{2001}{1999! + 2000! + 2001!} 
$$

## Бодлого 3

$x = \sqrt{a^2+a+1} - \sqrt{a^2-a+1}, a \in \mathbb{R}$ байг. Тэгвэл $x$-ийн боломжит бүх утгыг ол.

## Бодлого 4

Дараах нөхцөлийг хангах бүх бодит тоо $x$-ийг ол:

$$
10^x + 11^x + 12^x = 13^x + 14^x
$$

## Бодлого 5 (Korean Mathematics Competition 2001)

$f: \mathbb{N} \times \mathbb{N} \rightarrow \mathbb{N}$ функцийн хувьд $f(1, 1) = 2$ ба бүх $m, n \in \mathbb{N}$-ийн хувьд дараах нөхцөлүүдийг хангадаг байв:

$$
f(m+1, n) = f(m, n) + m \ \text{ба} \ f(m, n + 1) = f(m, n) - n
$$

Тэгвэл $f(p, q) = 2001$ байдаг бүх $(p, q)$ хосуудыг ол.

## Бодлого 6 (China 1983)

$f$ функц нь $[0, 1]$ завсарт бүх $a \neq b$-ийн хувьд дараах байдлаар тодорхойлогдоно:

$$
f(0) = f(1) = 1 \ \text{ба} \ |f(a) - f(b)| < |a - b|
$$

Тэгвэл дараах тэнцэтгэл бишийг батал:

$$
|f(a) - f(b)| < \frac{1}{2}
$$

## Бодлого 7

Дараах нөхцөлийг хангах бүх $(x, y)$ бүхэл тоон хосуудыг ол:

$$
x^3 + y^3 = (x + y)^2
$$

## Бодлого 8 (Korean Mathematics Competition 2001)

Бүх бодит тоо $x$-ийн хувьд

$$
f(x) = \frac{2}{4^x + 2}
$$

байг. Тэгвэл дараах илэрхийллийг тооцоол:

$$
f(\frac{1}{2001}) + f(\frac{2}{2001}) + \dots + f(\frac{2000}{2001})
$$

## Бодлого 9

Хэрвээ $n \geq 6$ бол дараах тэгшитгэлийг бүхэл тоон шийдтэй гэж батал:

$$
\frac{1}{x_1^2} + \frac{1}{x_2^2} + \dots + \frac{1}{x_n^2} = 1
$$

## Бодлого 10 (AIME 1988)

Дараах нөхцөлийг хангах бүх $(a, b)$ бүхэл тоон хосуудыг ол:

$$
ax^{17} + bx^{16} + 1
$$
олон гишүүнт нь $x^2 - x - 1$-д хуваагддаг.





