---
title: "Зуны бага сорилго №2.2"
subtitle: "ІІ сорил: 2025 оны 8 сарын 2"
format: html
lang: mn
---

_Бодох хугацаа 4 цаг 30 минут._  
_Бодлого бүр 7 оноотой._

---

### Бодлого 1

Эерэг бүхэл тоонуудаас бүрдэх олонлогийн ямар нэг гурван ялгаатай
элемент нь гурвалжны талуудын урт байх боломжтой бол уг олонлогийг гурвалжны шинжтэй гэж үзье.
$\{4, 5, 6, \ldots, n\}$ гэсэн дараалсан тоонуудын олонлогийн аль ч 10 элементтэй дэд олонлог нь гурвалжны шинжтэй байдаг хамгийн их $n$-ийг ол.

---

### Бодлого 2

$JHIZ$ нь тэгш өнцөгт байг. $A$ ба $C$ нь тус тус $ZI$ ба $ZJ$ тал дээр орших цэгүүд байг.
$A$ цэгээс $CH$ шулуунд буулгасан перпендикуляр нь $HI$ шулуунтай $X$ цэгт огтлолцоно. $C$ цэгээс $AH$ шулуунд буулгасан перпендикуляр нь $HJ$ шулуунтай $Y$ цэгт огтлолцоно.
Тэгвэл $X$, $Y$, $Z$ цэгүүд нэг шулуун дээр оршино гэж батал.

---

### Бодлого 3

Сүүлчийн гурван цифрийг нь арилгасан ч гэсэн төгс куб хэвээрээ үлдэх, $10$-д хуваагддаггүй бүх эерэг төгс куб тоонуудыг ол.

---

### Бодлого 4

$f:\mathbb{N} \to \mathbb{N}$ функц нь бүх $n$-ийн хувьд дараах нөхцөлүүдийг хангана:

$$
f(n+1) > f(n)
$$

$$
f(f(n)) = 3n
$$

Тэгвэл $f(2025)$-ийн утгыг ол.

---
